# Generated by Django 4.0.3 on 2022-04-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('排名', models.CharField(max_length=255, null=True)),
                ('标题', models.CharField(max_length=255, null=True)),
                ('热度', models.CharField(max_length=255, null=True)),
                ('种类', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('片名', models.CharField(max_length=255, null=True)),
                ('演员', models.CharField(max_length=255, null=True)),
                ('题材', models.CharField(max_length=255, null=True)),
                ('观看人数', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tube',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('剧名', models.CharField(max_length=255, null=True)),
                ('简介', models.CharField(max_length=255, null=True)),
                ('最近更新', models.CharField(max_length=255, null=True)),
                ('观看人数', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
